import type { Metadata } from "next";
import "./globals.css";
import Header from "./componenets/Header";
import Footer from "./componenets/Footer";
import { amazonEmber } from "./fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={amazonEmber.variable}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
